
const stages = [
  { n: '01', icon: '⌕', title: 'Discover', text: 'Search the web for relevant material and collect source metadata for your question.' },
  { n: '02', icon: '▤', title: 'Read', text: 'Extract available article text while respecting timeouts, size limits, and inaccessible pages.' },
  { n: '03', icon: '✳', title: 'Synthesize', text: 'Generate a structured report that connects ideas and links claims back to sources.' },
  { n: '04', icon: '✓', title: 'Critique', text: 'Review the evidence set for gaps, weaknesses, missing context, and uncertainty.' },
];

export default function About({ navigate }) {
  return <main className="about-page"><section className="about-hero container"><span className="eyebrow">BUILT FOR CURIOSITY</span><h1>Not another answer box.<br /><span className="gradient-text">A research process.</span></h1><p>ResearchOS turns a question into a focused research session. It brings source discovery, synthesis, and a quality critique into one place, while leaving the evidence visible for you to inspect.</p><button className="button button-primary" onClick={() => navigate('/app')}>Explore the workspace <span>↗</span></button></section><section className="container workflow-section"><div className="section-heading"><div><span className="eyebrow">THE WORKFLOW</span><h2>Four stages. One focused topic.</h2></div><p>Each session is designed around one research question. Start a new session when you want to investigate a different topic.</p></div><div className="workflow-grid">{stages.map((stage) => <article className="workflow-card" key={stage.n}><span className="workflow-number">{stage.n}</span><span className="workflow-icon">{stage.icon}</span><h3>{stage.title}</h3><p>{stage.text}</p></article>)}</div><div className="principles-row"><div><span className="principle-check">✓</span><div><strong>Traceable sources</strong><p>Inspect the links behind your report.</p></div></div><div><span className="principle-check">✓</span><div><strong>Honest limitations</strong><p>A critique is guidance, not proof of truth.</p></div></div><div><span className="principle-check">✓</span><div><strong>Session boundaries</strong><p>One topic stays one topic.</p></div></div></div></section></main>;
}
